import os
import json
import re
import logging
import urllib.request
import urllib.error
from typing import Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

class LLMClient:
    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.gemini_api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.openai_api_key = os.getenv("OPENAI_API_KEY")
        self.model = model or os.getenv("MODEL_NAME", "gemini-3.1-flash-lite")
        
        self.openai_client = None
        if self.openai_api_key and self.openai_api_key != "test_mock":
            try:
                import openai
                self.openai_client = openai.OpenAI(api_key=self.openai_api_key)
            except Exception as e:
                logger.warning(f"Could not initialize OpenAI client: {e}")

    def generate_json(self, system_prompt: str, user_prompt: str) -> Dict[str, Any]:
        # 1. Prefer Gemini if GEMINI_API_KEY is available and not test_mock
        if self.gemini_api_key and self.gemini_api_key != "test_mock":
            return self._generate_gemini(system_prompt, user_prompt)
        
        # 2. Try OpenAI if available
        if self.openai_client:
            return self._generate_openai(system_prompt, user_prompt)
            
        # 3. Fallback mock for testing
        return {
            "body": "This is a mocked LLM response for testing.",
            "cta": "test_cta",
            "rationale": "Mock rationale due to missing API key."
        }

    def _generate_gemini(self, system_prompt: str, user_prompt: str) -> Dict[str, Any]:
        models_to_try = [self.model, "gemini-3.1-flash-lite", "gemini-3.5-flash-lite", "gemini-3.8-flash"]
        # Deduplicate while preserving order
        models_to_try = list(dict.fromkeys(models_to_try))
        
        last_error = None
        for model in models_to_try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={self.gemini_api_key}"
            full_prompt = f"System Instructions:\n{system_prompt}\n\nUser Input:\n{user_prompt}\n\nOutput only valid JSON."
            body = json.dumps({
                "contents": [{"parts": [{"text": full_prompt}]}],
                "generationConfig": {
                    "responseMimeType": "application/json",
                    "temperature": 0.2,
                    "maxOutputTokens": 1500
                }
            }).encode("utf-8")
            
            req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
            try:
                with urllib.request.urlopen(req, timeout=30) as resp:
                    resp_data = json.loads(resp.read().decode("utf-8"))
                    text = resp_data["candidates"][0]["content"]["parts"][0]["text"]
                    
                    # Clean code fence if model included it
                    text = re.sub(r"^```json\s*", "", text.strip())
                    text = re.sub(r"\s*```$", "", text.strip())
                    
                    parsed = json.loads(text)
                    if isinstance(parsed, dict) and "body" in parsed:
                        return parsed
                    elif isinstance(parsed, dict):
                        return {
                            "body": parsed.get("message") or parsed.get("text") or str(parsed),
                            "cta": parsed.get("cta", "learn_more"),
                            "rationale": parsed.get("rationale", "Generated by Gemini")
                        }
            except urllib.error.HTTPError as e:
                err_body = e.read().decode("utf-8", errors="ignore")
                logger.warning(f"Gemini model {model} returned HTTP {e.code}: {err_body[:100]}")
                last_error = e
                # If 503 or 404, try next model
                if e.code in [404, 503]:
                    continue
                raise RuntimeError(f"Gemini API error ({e.code}): {err_body}")
            except Exception as e:
                logger.warning(f"Gemini model {model} error: {e}")
                last_error = e
                continue
                
        raise RuntimeError(f"All Gemini models failed. Last error: {last_error}")

    def _generate_openai(self, system_prompt: str, user_prompt: str) -> Dict[str, Any]:
        try:
            response = self.openai_client.chat.completions.create(
                model=os.getenv("MODEL_NAME", "gpt-4o-mini"),
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                response_format={"type": "json_object"}
            )
            content = response.choices[0].message.content
            return json.loads(content)
        except Exception as e:
            logger.error(f"OpenAI generation failed: {e}")
            raise RuntimeError(f"OpenAI failure: {e}")
